### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by rocket3989** [msbundles/avbert.com#2]
PS C:\Users\rocket3989\Downloads\Khan-master\Khan-master> py khan.py
Traceback (most recent call last):
  File "C:\Users\rocket3989\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\rocket3989\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\rocket3989\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "khan.py", line 18, in <module>
    browser = webdriver.Firefox()
  File "C:\Users\rocket3989\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "C:\Users\rocket3989\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

PS C:\Users\rocket3989\Downloads\Khan-master\Khan-master>

**Comment by msbundles** [comment]
You need to install gecko driver and firefox

**Comment by msbundles** [comment]
@rocket3989 Also please open all issues in the repo not this one
